variables:
  MAVEN_CLI_OPTS: "--show-version"
  # change this to your app directory
  APP_DIR: "/home/app/applications/toyota-hasjrat/hcare-asiist"
  # change this to your name app
  APP_NAME: "hcare-asiist"
  DOCKER_REGISTRY_HOSTED: "tabeldata.ip-dynamic.com:8087"
  DOCKER_REGISTRY_PUBLIC: "tabeldata.ip-dynamic.com:8088"
  DOCKER_USERNAME: "tabeldata"
  DOCKER_PASSWORD: "tabeldata"
cache:
  paths:
    - .m2/repository
    
rebuilding:
  stage: deploy
  before_script:
    - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean package'
  only:
    - /-release$/
  artifacts:
    paths:
      - target/*.jar
    name: $APP_NAME-$CI_COMMIT_TAG

docker-push:
  stage: deploy
  before_script:
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_HOSTED'
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_PUBLIC'
    - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean deploy'
  only:
    - /-final$/
