version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PasswordnyaSA2018
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql/
    networks:
      - postgres-network
  flyway-sqlserver:
    image: tabeldata.ip-dynamic.com:8088/flyway/flyway:6.0.8
    command: -url=jdbc:sqlserver://sqlserver:1433;databaseName=master -schemas=dbo -user=sa -password=PasswordnyaSA2018 -connectRetries=60 migrate
    volumes:
      - ./migration/sqlserver:/flyway/sql
    depends_on:
      - sqlserver
    networks:
      - postgres-network
  db2:
    image: tabeldata.ip-dynamic.com:8088/ibmcom/db2
    environment:
      - DBNAME=testdb
      - DB2INST1_PASSWORD=infinit
      - ARCHIVE_LOGS=false
      - LICENSE=accept
    ports:
      - 50000:50000
    volumes:
      - db2_data:/database
    privileged: true
    networks:
      - postgres-network
networks:
  postgres-network:
volumes:
  sqlserver_data:
  db2_data:
